const tabela2025 = [
    {
        nome: "Flamengo",
        sigla: "FLA",
        pontos: 24,
        jogos: 11,
        vitorias: 7,
        empates: 3,
        derrotas: 1,
        golsMarcados: 24,
        golsSofridos: 4,
        saldoGols: 20
    },
    {
        nome: "Cruzeiro",
        sigla: "CRU",
        pontos: 24,
        jogos: 12,
        vitorias: 7,
        empates: 3,
        derrotas: 2,
        golsMarcados: 17,
        golsSofridos: 8,
        saldoGols: 9
    },
    {
        nome: "Red Bull Bragantino",
        sigla: "RBB",
        pontos: 23,
        jogos: 12,
        vitorias: 7,
        empates: 2,
        derrotas: 3,
        golsMarcados: 14,
        golsSofridos: 11,
        saldoGols: 3
    },
    {
        nome: "Palmeiras",
        sigla: "PAL",
        pontos: 22,
        jogos: 11,
        vitorias: 7,
        empates: 1,
        derrotas: 3,
        golsMarcados: 12,
        golsSofridos: 8,
        saldoGols: 4
    },
    {
        nome: "Bahia",
        sigla: "BAH",
        pontos: 21,
        jogos: 12,
        vitorias: 6,
        empates: 3,
        derrotas: 3,
        golsMarcados: 14,
        golsSofridos: 11,
        saldoGols: 3
    },
    {
        nome: "Fluminense",
        sigla: "FLU",
        pontos: 20,
        jogos: 11,
        vitorias: 6,
        empates: 2,
        derrotas: 3,
        golsMarcados: 15,
        golsSofridos: 12,
        saldoGols: 3
    },
    {
        nome: "Atlético-MG",
        sigla: "CAM",
        pontos: 20,
        jogos: 12,
        vitorias: 5,
        empates: 5,
        derrotas: 2,
        golsMarcados: 13,
        golsSofridos: 10,
        saldoGols: 3
    },
    {
        nome: "Botafogo",
        sigla: "BOT",
        pontos: 18,
        jogos: 11,
        vitorias: 5,
        empates: 3,
        derrotas: 3,
        golsMarcados: 14,
        golsSofridos: 7,
        saldoGols: 7
    },
    {
        nome: "Mirassol",
        sigla: "MIR",
        pontos: 17,
        jogos: 11,
        vitorias: 4,
        empates: 5,
        derrotas: 2,
        golsMarcados: 17,
        golsSofridos: 12,
        saldoGols: 5
    },
    {
        nome: "Corinthians",
        sigla: "COR",
        pontos: 16,
        jogos: 12,
        vitorias: 4,
        empates: 4,
        derrotas: 4,
        golsMarcados: 13,
        golsSofridos: 15,
        saldoGols: -2
    },
    {
        nome: "Grêmio",
        sigla: "GRE",
        pontos: 16,
        jogos: 12,
        vitorias: 4,
        empates: 4,
        derrotas: 4,
        golsMarcados: 12,
        golsSofridos: 15,
        saldoGols: -3
    },
    {
        nome: "Ceará",
        sigla: "CEA",
        pontos: 15,
        jogos: 11,
        vitorias: 4,
        empates: 3,
        derrotas: 4,
        golsMarcados: 13,
        golsSofridos: 11,
        saldoGols: 2
    },
    {
        nome: "Vasco da Gama",
        sigla: "VAS",
        pontos: 13,
        jogos: 12,
        vitorias: 4,
        empates: 1,
        derrotas: 7,
        golsMarcados: 14,
        golsSofridos: 16,
        saldoGols: -2
    },
    {
        nome: "São Paulo",
        sigla: "SAO",
        pontos: 12,
        jogos: 12,
        vitorias: 2,
        empates: 6,
        derrotas: 4,
        golsMarcados: 10,
        golsSofridos: 14,
        saldoGols: -4
    },
    {
        nome: "Santos",
        sigla: "SAN",
        pontos: 11,
        jogos: 12,
        vitorias: 3,
        empates: 2,
        derrotas: 7,
        golsMarcados: 11,
        golsSofridos: 14,
        saldoGols: -3
    },
    {
        nome: "Vitória",
        sigla: "VIT",
        pontos: 11,
        jogos: 12,
        vitorias: 2,
        empates: 5,
        derrotas: 5,
        golsMarcados: 10,
        golsSofridos: 14,
        saldoGols: -4
    },
    {
        nome: "Internacional",
        sigla: "INT",
        pontos: 11,
        jogos: 12,
        vitorias: 2,
        empates: 5,
        derrotas: 5,
        golsMarcados: 12,
        golsSofridos: 18,
        saldoGols: -6
    },
    {
        nome: "Fortaleza",
        sigla: "FOR",
        pontos: 10,
        jogos: 12,
        vitorias: 2,
        empates: 4,
        derrotas: 6,
        golsMarcados: 12,
        golsSofridos: 18,
        saldoGols: -6
    },
    {
        nome: "Juventude",
        sigla: "JUV",
        pontos: 8,
        jogos: 11,
        vitorias: 2,
        empates: 2,
        derrotas: 7,
        golsMarcados: 8,
        golsSofridos: 24,
        saldoGols: -16
    },
    {
        nome: "Sport",
        sigla: "SPT",
        pontos: 3,
        jogos: 11,
        vitorias: 0,
        empates: 3,
        derrotas: 8,
        golsMarcados: 5,
        golsSofridos: 18,
        saldoGols: -13
    }
];

export default tabela2025;